### ISSUE TITLE
DataSourceInterface API broken

### ISSUE THREAD

**Issue by camspiers** [heyday/silverstripe-redirects#6]
The `DataSourceInterface` interface is now kinda broken, because `DataListDataSource` returns an associative array (which Redirector now expects), but all the other data sources were not changed to respect this new interface (nor was it documented in the interface itself).

My suggestion is to remove the `get` function and add a new `match` function to the `DataSourceInterface`, and use this instead, and keep the performance optimizations to the data sources themselves. The match function would return a `Redirect` if one was found, and return `null` if not, and then Redirector (you'll have to figure out how exactly to do the cached version) can be refactored to just do:

``` php
public function getRedirectForRequest(\SS_HTTPRequest $request) {
    $url = Redirect::formatUrl($request->getURL());
    $redirect = $this->dataSource->match($url);
    return $redirect ?: false;
}
```

https://github.com/heyday/silverstripe-redirects/blob/master/src/DataSourceInterface.php#L5-L11
https://github.com/heyday/silverstripe-redirects/blob/master/src/DataSourceInterface.php#L8
https://github.com/heyday/silverstripe-redirects/blob/master/src/Redirector.php#L29
https://github.com/heyday/silverstripe-redirects/blob/master/src/DataSource/YamlDataSource.php#L22
https://github.com/heyday/silverstripe-redirects/blob/master/src/DataSource/GroupedDataSource.php#L30-L33

**Comment by timhiggs** [comment]
Hey Cam!  OK - sounds like a reasonable alternative suggestion.  Will have a bit more of a look through.

**Comment by camspiers** [comment]
Awesome, thanks @timhiggs!
